### ISSUE TITLE
open menu key

### ISSUE THREAD

**Issue by imthecheeser** [ExFFFF0000/GrenadeHelper#1]
whats the key to open the menu ive tried like every key and it doesnt work

**Comment by ExFFFF0000** [comment]
no any key about show/hide this menu.

**Comment by imthecheeser** [comment]
> no any key about show/hide this menu.

but how do i activate the grenade helper then? the menu doesnt load up like the menu i saw in ur screenshot

**Comment by ExFFFF0000** [comment]
> Author

Click the Login button

**Comment by imthecheeser** [comment]
> > Author
> 
> Click the Login button

ofc i did lol it just doesnt work

**Comment by ExFFFF0000** [comment]
> > > Author 作者
> > 
> > 
> > Click the Login button 点击登录按钮
> 
> ofc i did lol it just doesnt workofc我做了lol它只是不工作

use cs2-dumper to update offsets.
